name: CD
on:
    push:
        branches: [ main ]
permissions:
    id-token: write
    contents: read
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Login to ECR
              id: ecr
              uses: aws-actions/amazon-ecr-login@v2
            - name: Build & Push
              env:
                ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
              run: |
                IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:latest
                docker build -t $IMAGE_URI .
                docker push $IMAGE_URI
            - name: Force new deployment
              env:
                CLUSTER: ${{ secrets.ECS_CLUSTER }}
                SERVICE: ${{ secrets.ECS_SERVICE }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                aws ecs update-service \
                    --cluster "$CLUSTER" \
                    --service "$SERVICE" \
                    --force-new-deployment \
                    --region "$AWS_REGION"